#!/bin/bash
# ================================ HEADER =====================================
# Author:       Loic Delineau
# Date:         01/04/2025
# Licence:     	GNU-GPLv3 
# File:        	generate
# Platform :    Linux shell running the Bourne Again SHell (BASH)
# Description:	Generates the certificates

# ======================= GLOBAL VARIABLES ====================================
black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)

# =========================== SCRIPT EXECUTION ================================


while IFS=',' read -r firstname lastname place; do
	pdflatex certificate.tex 
	rm certificate.aux certificate.log
	open certificate.pdf
	echo "First Name: $firstname"
	echo "Last Name: $lastname"
	echo "Place: $place"
	echo "---"
done < results.csv


exit

for ((i=1; i<=$tot; ++i))



# ========================== Closing Messages ================================= 
echo "$green"
echo "Script was executed successfully! $white"
echo ""
echo "Details of this script are documented here:"
echo "https://github.com/loicdelineau/"
echo ""
echo "Made,"
echo "with Love,"
echo "by Loïc"
echo ""


